// ─── Git Automation Service ─────────────────────────────────
// Handles branch creation, staging, committing, and pushing generated code

import type { SimpleGit } from "simple-git";
import { simpleGit } from "simple-git";
import type { GenerationResult } from "../types/design.types";
import { createLogger } from "../utils/logger";
import { writeFile, mkdir } from "fs/promises";
import path from "path";

const log = createLogger("git-service");

// ─── Configuration ──────────────────────────────────────────

const REPO_ROOT = process.cwd();

function getGit(): SimpleGit {
  return simpleGit(REPO_ROOT);
}

// ─── Branch Management ──────────────────────────────────────

/**
 * Create a new design branch from the current HEAD.
 * Branch format: design/YYYYMMDD-HHmmss-{fileId}
 */
export async function createDesignBranch(figmaFileId: string): Promise<string> {
  const git = getGit();
  const timestamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const shortId = figmaFileId.slice(0, 8);
  const branchName = `design/${timestamp}-${shortId}`;

  log.info("Creating design branch", { branchName });

  // Ensure we're on latest main
  try {
    await git.fetch("origin", "main");
    await git.checkout("main");
    await git.pull("origin", "main");
  } catch (err) {
    log.warn("Could not update main, creating branch from current HEAD", {
      error: err instanceof Error ? err.message : String(err),
    });
  }

  await git.checkoutLocalBranch(branchName);
  log.info("Branch created", { branchName });

  return branchName;
}

// ─── File Writing ───────────────────────────────────────────

/**
 * Write all generated files to the repository working directory.
 */
export async function writeGeneratedFiles(result: GenerationResult): Promise<string[]> {
  const writtenFiles: string[] = [];

  // Write components
  for (const component of result.components) {
    const filePath = path.join(REPO_ROOT, component.path, component.filename);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, component.content, "utf-8");
    writtenFiles.push(path.join(component.path, component.filename));
    log.debug("Wrote component", { file: filePath });
  }

  // Write pages
  for (const page of result.pages) {
    const filePath = path.join(REPO_ROOT, page.path, page.filename);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, page.content, "utf-8");
    writtenFiles.push(path.join(page.path, page.filename));
    log.debug("Wrote page", { file: filePath });
  }

  // Write design metadata
  const metadataPath = path.join(REPO_ROOT, ".design-metadata.json");
  await writeFile(metadataPath, JSON.stringify(result.metadata, null, 2), "utf-8");
  writtenFiles.push(".design-metadata.json");

  log.info("Generated files written", { count: writtenFiles.length });
  return writtenFiles;
}

// ─── Commit & Push ──────────────────────────────────────────

/**
 * Stage, commit, and push all generated files.
 */
export async function commitAndPush(
  branchName: string,
  result: GenerationResult,
  files: string[]
): Promise<{ commitSha: string; branchName: string }> {
  const git = getGit();
  const { metadata } = result;

  // Stage files
  log.info("Staging generated files", { count: files.length });
  for (const file of files) {
    await git.add(file);
  }

  // Also stage any downloaded assets
  try {
    await git.add("public/assets/");
  } catch {
    // No assets to stage
  }

  // Build commit message
  const commitMessage = `feat: auto-generate pages from Figma design

Figma File ID: ${metadata.figmaFileId}
Design Version: ${metadata.figmaVersion}
Generated At: ${metadata.generatedAt}

Components: ${metadata.componentCount}
Pages: ${metadata.pageCount}
Generation Time: ${metadata.generationDurationMs}ms

Generated by: martech-website-builder v1.0`;

  // Commit
  log.info("Creating commit");
  const commitResult = await git.commit(commitMessage);
  const commitSha = commitResult.commit || "unknown";
  log.info("Commit created", { commitSha });

  // Push
  log.info("Pushing to remote", { branch: branchName });
  await git.push("origin", branchName, ["--set-upstream"]);
  log.info("Push complete", { branch: branchName, commitSha });

  return { commitSha, branchName };
}

/**
 * Full git workflow: create branch → write files → commit → push
 */
export async function gitPublish(
  figmaFileId: string,
  result: GenerationResult
): Promise<{
  branchName: string;
  commitSha: string;
  filesWritten: number;
}> {
  return log.timed("Git publish", async () => {
    // 1. Create branch
    const branchName = await createDesignBranch(figmaFileId);

    // 2. Write files
    const files = await writeGeneratedFiles(result);

    // 3. Commit and push
    const { commitSha } = await commitAndPush(branchName, result, files);

    return {
      branchName,
      commitSha,
      filesWritten: files.length,
    };
  });
}
